data_root: datasets/amazon
use_memory: False
augmentation:
    file_prefix: amazon_backtranslate
    enabled: True
    type: support # append | replace | support
    max_temperature: 1
    min_temperature: 1
