includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/ANIL.yaml
  - backbones/bert.yaml


device_ids: 0
way_num: 5
shot_num: 1
query_num: 15
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 15
episode_size: 1
train_episode: 100
test_episode: 100
