includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/bert.yaml


device_ids: 0
way_num: 5
shot_num: 5
query_num: 10
test_way: 5 # use ~ -> test_* = *_num
test_shot: 5
test_query: 20
episode_size: 1
train_episode: 50
test_episode: 10
